config/routes.rb
Rails.application.routes.draw do
  # resources :controller_name --> creates six different routes in your application, all mapping to the timeline controller
  resources :timeline do
    member do
      get "like", to: "timeline#upvote"
      get "dislike", to: "timeline#downvote"
    end
  end

  devise_for :users
  get 'home' => "pages#home"
  root "pages#index"
  get 'about' => "pages#about"

  # associate '/write' & '/comment' & '/destroy' & '/edit' to 'write' & 'comment' & 'destroy' & 'edit' action in timeline controller
  post '/write' => 'timeline#write'
  post '/comment' => 'timeline#comment'
  post '/update_post' => 'timeline#update_post'
  post '/update_comment' => 'timeline#update_comment'
  get '/view_post' => 'timeline#view_post'
  get '/edit_post' => 'timeline#edit_post'
  get '/edit_comment' => 'timeline#edit_comment'
  get '/destroy' => 'timeline#destroy'
  get '/destroy_comment' => 'timeline#destroy_comment'


  get 'portfolio' => "pages#portfolio"
  get 'sample' => "pages#sample"
  get 'contact' => "pages#contact"

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :user
  belongs_to :post
end

app/models/pin.rb
class Pin < ActiveRecord::Base
	belongs_to :user
	has_attached_file :image, :styles => { :medium => "300x300>", :thumb => "100x100>" }
	validates_attachment_content_type :image, :content_type => ["image/jpg", "image/jpeg", "image/png", "image/gif"]

end

# class User < ActiveRecord::Base
# has_attached_file :avatar, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png"
# validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/
# end

app/models/post.rb
class Post < ActiveRecord::Base
  acts_as_votable
  belongs_to :user
  has_many :comments

  has_attached_file :image, styles: { medium: "700x500>", small: "350x250>" },
  :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # attr_accessor :name, :email
  has_many :posts
  has_many :comments
  has_many :pins
end


class AddUserIdToPosts < ActiveRecord::Migration
  def change
    add_column :pins, :user_id, :integer
    add_index :pins, :user_id
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def about
  end

  #  def portfolio
  #  pdf_filename = File.join(Rails.root, "tmp/resume.pdf")
  #  send_file(pdf_filename, :filename => "resume.pdf", :disposition => 'inline', :type => "application/pdf")
  # end
end

app/controllers/pins_controller.rb
class PinsController < ApplicationController
  # before_action :set_pin, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]
  before_action :set_pin, only: [:show, :edit, :update, :destroy]
  before_action :correct_user, only: [:edit, :update, :destroy]

  def index
    @pins = Pin.all
  end

  def show
  end

  def new
    @pin = current_user.pins.build
  end

  def edit
  end

  def create
    @pin = current_user.pins.build(pin_params)

    if @pin.save
      redirect_to @pin, notice: 'Pin was successfully created.'
    else
      render :new
    end
  end

  def update
    respond_to do |format|
      if @pin.update(pin_params)
        redirect_to @pin, notice: 'Pin was successfully updated.'
      else
        render :edit
      end
    end
  end

  def destroy
    @pin.destroy
    respond_to do |format|
      format.html { redirect_to pins_url, notice: 'Pin was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  def set_pin
    @pin = Pin.find(params[:id])
  end

  def correct_user
    @pin = current_user.pins.find_by(id: params[:id])
    redirect_to pins_path, notice: "Not authorized to edit this pin" if @pin.nil?
  end

  # what you permit for the user to be able to update in the form
  def pin_params
    params.require(:pin).permit(:description, :image)
  end
end

app/controllers/timeline_controller.rb
class TimelineController < ApplicationController
  before_action :authenticate_user!, except: [:show, :view_post] # requires login to write posts or comments

  def index
    @posts = Post.all.reverse # the most recent post on top
  end

  def show
    @post = Post.all.order("updated_at DESC") # another way to list them in descending order
    logger.info @post
  end

  def view_post
    @post = Post.find(params[:post_id])
    @comments = Comment.where(post_id: @post)
    if Post.where.not(id: @post).count == 0
      @random_post = @post
      puts @random_post
    else
      @random_post = Post.where.not(id: @post).order("RANDOM()").first
    end
  end

  def new
    @post = current_user.posts.build
  end

  def write
    # save text through 'content' params and redirect back to the timeline page
    # current_user : user that is currently signed in to wrtie

    # before : Post.create(user_id: current_user.id, content: params[:post_content])
    @post = current_user.posts.build(post_params)
    # @post = Post.new(title: params[:post_title], content: params[:post_content], image: params[:image])
    @post.user = current_user
    if @post.save
      redirect_to '/timeline/show'
    else
      render 'new'
    end
  end

  def comment
    #  Creating comments accepts two parameters: post_id & comment_content
    # before: Comment.create(user_id: current_user.id, post_id: params[:post_id], msg: params[:comment_content])
    @post = Post.find(params[:post_id])
    @comment = Comment.new(post_id: params[:post_id],
                           msg: params[:comment_content])
    @comment.user = current_user
    if @comment.save
      redirect_to :back
    end
  end

  def edit_post
    #  find a post of the corresponding id and store it into an instance variable
    # takes :post_id parameters from index page and store it into @post to be used in edit_post page
    # this def behaves like a bridge

    # authenticate the post writer
    @post = Post.find(params[:id])
  end

  def edit_comment
    # authenticate the comment writer
    if current_user == Comment.find(params[:comment_id]).user
      @comment = Comment.find(params[:comment_id])
    else
      flash[:notice] = "You cannot edit this!"
      redirect_to :back
    end
  end

  def update_post
    @post = Post.find(params[:post_id])
    @post.title = params[:title]
    @post.content = params[:content]
    post_id = @post.id
    # save the change in the database
    @post.save
    # passing a param value when redirect_to another action
    redirect_to controller: 'timeline', action: 'view_post', post_id: @post.id
  end

  def update_comment
    @comment = Comment.find(params[:comment_id])
    @comment.msg = params[:comment_content]
    @comment.save
    redirect_to controller: 'timeline', action: 'view_post', post_id: @comment.post_id
  end

  def destroy
    @post = Post.find(params[:id])
    @comments = Comment.where(post_id: @post)
    # authenticate the post writer
    if current_user == @post.user
      # delets all the comments that belong to @post

      @comments.each do |comment|
        comment_belonging = Comment.find(comment.id)
        comment_belonging.destroy
      end
      @post.destroy
      redirect_to '/timeline/show'
    else
      flash[:notice] = "You cannot destroy this!"
      redirect_to :back
    end
  end

  def destroy_comment
    # authenticate the comment writer
    if current_user == Comment.find(params[:comment_id]).user
      @comment = Comment.find(params[:comment_id])
      @comment.destroy
      redirect_to :back
    else
      flash[:notice] = "You cannot destroy this!"
      redirect_to :back
    end
  end

  def upvote
    @post = Post.find(params[:id])
    @post.liked_by current_user
    redirect_to :back
  end

  def downvote
    @post = Post.find(params[:id])
    @post.downvote_from current_user
    redirect_to :back
  end

  private

  def post_params
    params.permit(:title, :content, :image)
  end

  def find_post
    @post = Post.find(params[:id])
  end

end # need this

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/pins_helper.rb
module PinsHelper
end

app/helpers/timeline_helper.rb
module TimelineHelper
end

app/views/layouts/_footer.html.erb
<footer>
  <div class="container">
    <div class="row">
      <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
        <ul class="list-inline text-center">
          <li>
            <a href="http://www.facebook.com/JunKim0922" target= "_blank">
              <span class="fa-stack fa-lg">
                <i class="fa fa-circle fa-stack-2x"></i>
                <i class="fa fa-facebook fa-stack-1x fa-inverse"></i>
              </span>
            </a>
          </li>
          <li>
            <a href="https://github.com/j464kim" target= "_blank">
              <span class="fa-stack fa-lg">
                <i class="fa fa-circle fa-stack-2x"></i>
                <i class="fa fa-github fa-stack-1x fa-inverse"></i>
              </span>
            </a>
          </li>
          <li>
            <a href= "https://www.linkedin.com/in/kwnsrnjs12" target= "_blank">
              <span class="fa-stack fa-lg">
                <i class="fa fa-circle fa-stack-2x"></i>
                <i class="fa fa-linkedin fa-stack-1x fa-inverse"></i>
              </span>
            </a>
          </li><hr>
        </ul>
        <center> <p class="copyright text-muted">Copyright &copy; Jun-Gwon_Kim 2016</p></center>
      </div>
    </div>
  </div>
</footer>

app/views/layouts/_header.html.erb
<!-- Navigation -->

<nav class="navbar navbar-default navbar-custom navbar-fixed-top">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header page-scroll">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "Jun-Gwon's Blog", root_path, class: "navbar-brand" %>
    </div>

  <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home", root_path %></li>
        <li><%= link_to "About", about_path %></li>
        <li><%= link_to "Post", '/timeline/show' %></li>
        <!-- <li><%= link_to "Portfolio", portfolio_path %></li> -->

        <!-- # log in & log out Setting -->
        <% if user_signed_in? %>
          <li><%= link_to "Account Setting", edit_user_registration_path %><li>
          <li><%= link_to "Log out", destroy_user_session_path, method: :delete %></li>
        <% else %>
          <li><%= link_to "Sign in", new_user_session_path %></li>
        <% end %>
      </ul>
    </div>
  <!-- /.navbar-collapse -->
  </div>
  <!-- /.container -->
</nav>
<br><br>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html large="en">
<link rel="stylesheet" href="http://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.4.0/css/font-awesome.min.css">
<head>
	<title><%= yield(:title) %>Welcome to Jun's App!</title>
<%= stylesheet_link_tag 'application', media: 'all',
  'data-turbolinks-track' => true %>

    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  <title>Personal</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1">
	<%= render partial: 'layouts/header' %><br>
</head>
<body>
  <div class="wrapper">
		<%= yield %>
	</div>
</body>
<foot>
	<br><br><br><br>
	<%= render 'layouts/footer' %>
</foot>
</html>

app/views/pages/about.html.erb
<div class="row">
    <div class="box">
        <div class="col-lg-12 text-center">
            <div id="carousel-example-generic" class="carousel slide">
                <!-- Indicators -->
                <ol class="carousel-indicators hidden-xs">
                    <li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
                    <li data-target="#carousel-example-generic" data-slide-to="1"></li>
                    <li data-target="#carousel-example-generic" data-slide-to="2"></li>
                    <li data-target="#carousel-example-generic" data-slide-to="3"></li>
                </ol>

                <!-- Wrapper for slides -->
                <div class="carousel-inner">
                    <div class="item active">
                        <!-- <img class="img-responsive img-full" src="assets/waterloo.jpg" alt=""> -->
                        <a href="http://uwaterloo.ca" class="portfolio-box">
                            <img src="/assets/waterloo" class="img-responsive" >
                            <div class="portfolio-box-caption">
                                <div class="portfolio-box-caption-content">
                                    <div class="project-category text-faded">
                                        Education
                                    </div>
                                    <div class="project-name">
                                        University of Waterloo
                                    </div>
                                </div>
                            </div>
                        </a>

                    </div>
                    <div class="item">
                        <!-- <img class="img-responsive img-full" src="assets/hybrid.jpg" alt=""> -->
                        <a href="http://uwh-webapp.com" class="portfolio-box">
                            <img src="/assets/hybrid" class="img-responsive" alt="" >
                            <div class="portfolio-box-caption">
                                <div class="portfolio-box-caption-content">
                                    <div class="project-category text-faded">
                                        Engineering Group
                                    </div>
                                    <div class="project-name">
                                        Waterloo Hybrid
                                    </div>
                                </div>
                            </div>
                        </a>

                    </div>
                    <div class="item">
                        <!-- <img class="img-responsive img-full" src="assets/vanier.jpg" alt=""> -->
                        <a href="http://www.vaniercollege.qc.ca" class="portfolio-box">
                            <img src="/assets/vanier" class="img-responsive" alt="" >
                            <div class="portfolio-box-caption">
                                <div class="portfolio-box-caption-content">
                                    <div class="project-category text-faded">
                                        Education
                                    </div>
                                    <div class="project-name">
                                        Cégep Vanier
                                    </div>
                                </div>
                            </div>
                        </a>

                    </div>
                    <div class="item">
                        <!-- <img class="img-responsive img-full" src="assets/mchack.jpg" alt=""> -->
                        <a href="https://www.mchacks.io" class="portfolio-box">
                            <img src="/assets/mchack" class="img-responsive" alt="" >
                            <div class="portfolio-box-caption">
                                <div class="portfolio-box-caption-content">
                                    <div class="project-category text-faded">
                                        Competition
                                    </div>
                                    <div class="project-name">
                                        McGill Hackathon
                                    </div>
                                </div>
                            </div>
                        </a>

                    </div>
                </div>

                <!-- Controls -->
                <a class="left carousel-control" href="#carousel-example-generic" data-slide="prev">
                    <span class="icon-prev"></span>
                </a>
                <a class="right carousel-control" href="#carousel-example-generic" data-slide="next">
                    <span class="icon-next"></span>
                </a>
            </div>
        </div>
    </div>
</div>
<br>

 <!-- <div class="row">
            <div class="box">
                <div class="col-lg-12">
                    <hr>
                    <h2 class="intro-text text-center">University of
                        <strong>Waterloo</strong>
                    </h2>
                    <hr>
                    <img class="img-responsive img-border img-left" src="assets/waterloo.jpg" alt="">
                    <hr class="visible-xs">
                    <p>The boxes used in this template are nested inbetween a normal Bootstrap row and the start of your column layout. The boxes will be full-width boxes, so if you want to make them smaller then you will need to customize.</p>
                    <p>A huge thanks to <a href="http://join.deathtothestockphoto.com/" target="_blank">Death to the Stock Photo</a> for allowing us to use the beautiful photos that make this template really come to life. When using this template, make sure your photos are decent. Also make sure that the file size on your photos is kept to a minumum to keep load times to a minimum.</p>
                    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc placerat diam quis nisl vestibulum dignissim. In hac habitasse platea dictumst. Interdum et malesuada fames ac ante ipsum primis in faucibus. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas.</p>
                </div>
            </div>
        </div> -->



<!-- <h1 class="text-center">About</h1>
  <section class="no-padding" id="portfolio">
        <div class="container-fluid">
            <div class="row no-gutter">
                    <div class="col-lg-4 col-sm-6">
                        <a href="http://uwaterloo.ca" class="portfolio-box">
                            <img src="/assets/waterloo" class="img-responsive" >
                            <div class="portfolio-box-caption">
                                <div class="portfolio-box-caption-content">
                                    <div class="project-category text-faded">
                                        Education
                                    </div>
                                    <div class="project-name">
                                        University of Waterloo
                                    </div>
                                </div>
                            </div>
                        </a>
                    </div>


                    <div class="col-lg-4 col-sm-6">
                        <a href="https://en.wikipedia.org/wiki/Toronto" class="portfolio-box">
                             <img src="/assets/toronto" class="img-responsive" alt="">
                            <div class="portfolio-box-caption">
                                <div class="portfolio-box-caption-content">
                                    <div class="project-category text-faded">
                                        City
                                    </div>
                                    <div class="project-name">
                                        Toronto
                                    </div>
                                </div>
                            </div>
                        </a>
                    </div>

                    <div class="col-lg-4 col-sm-6">
                        <a href="http://www.vaniercollege.qc.ca" class="portfolio-box">
                            <img src="/assets/vanier" class="img-responsive" alt="" >
                            <div class="portfolio-box-caption">
                                <div class="portfolio-box-caption-content">
                                    <div class="project-category text-faded">
                                        Education
                                    </div>
                                    <div class="project-name">
                                        Cégep Vanier
                                    </div>
                                </div>
                            </div>
                        </a>
                    </div>
                    <div class="col-lg-4 col-sm-6">
                        <a href="https://en.wikipedia.org/wiki/Montreal" class="portfolio-box">
                            <img src="/assets/montreal" class="img-responsive" alt="">
                            <div class="portfolio-box-caption">
                                <div class="portfolio-box-caption-content">
                                    <div class="project-category text-faded">
                                        City
                                    </div>
                                    <div class="project-name">
                                        Montreal
                                    </div>
                                </div>
                            </div>
                        </a>
                    </div>
                    <div class="col-lg-4 col-sm-6">
                        <a href="http://uwh-webapp.com" class="portfolio-box">
                            <img src="/assets/hybrid" class="img-responsive" alt="">
                            <div class="portfolio-box-caption">
                                <div class="portfolio-box-caption-content">
                                    <div class="project-category text-faded">
                                        Activity
                                    </div>
                                    <div class="project-name">
                                        Waterloo Hybrid
                                    </div>
                                </div>
                            </div>
                        </a>
                    </div>
                    <div class="col-lg-4 col-sm-6">
                        <a href="https://en.wikipedia.org/wiki/Korea" class="portfolio-box">
                            <img src="/assets/korea" class="img-responsive" alt="">
                            <div class="portfolio-box-caption">
                                <div class="portfolio-box-caption-content">
                                    <div class="project-category text-faded">
                                        Nation
                                    </div>
                                    <div class="project-name">
                                        Korea
                                    </div>
                                </div>
                            </div>
                        </a>
                    </div>
                <div class="col-lg-4 col-sm-6">
                    <a href="https://en.wikipedia.org/wiki/Canada" class="portfolio-box">
                        <img src="/assets/canada" class="img-responsive" alt="">
                        <div class="portfolio-box-caption">
                            <div class="portfolio-box-caption-content">
                                <div class="project-category text-faded">
                                    Nation
                                </div>
                                <div class="project-name">
                                    Canada
                                </div>
                            </div>
                        </div>
                    </a>
                </div>
            </div>
        </div>
    </section> -->

app/views/pages/contact.html.erb
<h1>Say Hello!</h1>

app/views/pages/home.html.erb
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <!--
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    -->

    <title>JunGwon Kim</title>

    <!-- Bootstrap Core CSS -->
    <link href="css/bootstrap.min.css" rel="stylesheet">

</head>
<body>

 <header class="intro-header" style="background-image: url(assets/2.jpg)">
        <div class="container">
            <div class="row">
                <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
                    <div class="site-heading">
                        <h1><font color="#5bc0de">JunGwon Kim</font></h1>
                        <hr class="small">
                        <span class="subheading"><font color="#5cb85c">Welcome to Jun's Blog !</font></span>

                        <P> </P>
                        <% if user_signed_in? %>
                           <!-- do something -->
                         <% else %>
                            <p>
                        <%= link_to "Sign up", new_user_registration_path, class: "btn btn-default btn-lg" %>
                        <%= link_to "Log in", new_user_session_path, class: "btn btn-primary btn-lg" %>
                            </p>
                      <% end %>
                    </div>
                </div>
            </div>
        </div>


 </header>

</body>


</html>

app/views/pages/portfolio.html.erb
<hr>
<div class="text-center">
 <!-- <img src="/assets/resume.png" width="950" height="1200" alt="Icon" /> -->
</div>

app/views/pins/_form.html.erb
<%= form_for @pin, html: {multipart: true} do |f| %>

  <% if @pin.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@pin.errors.count, "error") %> prohibited this pin from being saved:</h2>

      <ul>
      <% @pin.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :image %>
    <%= f.file_field :image, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :description %>
    <%= f.text_field :description, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.submit class: "btn btn-primary" %>
  </div>
<% end %>

app/views/pins/edit.html.erb
<hr>

<h1>Editing Pin</h1>
<%= render 'form' %>

<%= link_to 'Show', @pin %> |
<%= link_to 'Back', pins_path %>

app/views/pins/index.html.erb
<hr>
<p id="notice"><%= notice %></p>
<h1>Listing Pins</h1>

<table>
  <thead>
    <tr>
      <th>Image</th>
      <th>Description</th>
      <th>User</th>
      <!-- <th colspan="3"></th> -->
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @pins.each do |pin| %>
      <tr>
        <th><%= image_tag pin.image.url(:thumb) %></th>
        <td><%= pin.description %></td>
      <!-- <td><%= pin.user.try(:email) %></td> -->
        <td><%= pin.user.email if pin.user %></td>
      <!--   , pin <=> , pin_path(pin) -->
        <td><%= link_to 'Show', pin %></td>
        <% if pin.user == current_user %>
        <td><%= link_to 'Edit', edit_pin_path(pin) %></td>
        <td><%= link_to 'Destroy', pin, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<% if user_signed_in? %>
<%= link_to 'New Pin', new_pin_path %>
<% end %>

app/views/pins/new.html.erb
<hr>
<h1>New Pin</h1>


<%= render 'form' %>

<%= link_to 'Back', pins_path %>

app/views/timeline/_random_post.html.erb
<div id="random_post">
  <h3>Random Post</h3>
  <div class="post">
    <div class="post_image">
      <%= link_to (image_tag @random_post.image.url(:medium)), view_post_path(:post_id => @random_post.id) %>
    </div>
    <div class="post_content">
      <div class="title">
        <h2>
          <%= link_to @random_post.title, view_post_path(:post_id => @random_post.id) %>
        </h2>
      </div>
      <div class="data clearfix">
        <p class="username">
          Shared by ID #
          <%= @random_post.user_id %>  -- about <%= time_ago_in_words(@random_post.created_at) %> ago
        </p>
        <p class="buttons">
          <span>
            <i class="fa fa-comments-o"></i>
            <%= @random_post.comments.count %>
          </span>
          <span>
            <i class="fa fa-thumbs-o-up"></i>
            <%= @random_post.get_likes.size %>
          </span>
        </p>
      </div>
    </div>
  </div>
</div>

app/views/timeline/view_post.html.erb
<div id="post_show">
  <h1><%= @post.title %></h1>
  <p class="username"> Shared by ID #<%= @post.user_id %> -- about <%= time_ago_in_words(@post.created_at) %> ago<br>
  </p>

  <div class="clearfix">
    <div class="post_image_description">
      <%= form_tag '/view_post', method: "post" do %>
          <!-- to let update action know which post to be updated, -->
          <%= link_to (image_tag @post.image.url(:medium)), view_post_path(:post_id => @post.id) %>

          <!-- <%= @post.content %> displays original post content -->
          <pre name="post_content"><%= @post.content %></pre>
      <% end %>
    </div>

    <div class="post_data">
      <%= link_to like_timeline_path(@post), method: :get, class: "data" do %>
          <i class="fa fa-thumbs-o-up"></i>
          <%= pluralize(@post.get_upvotes.size, "Like") %>
      <% end %>
      <%= link_to dislike_timeline_path(@post), method: :get, class: "data" do %>
          <i class="fa fa-thumbs-o-down"></i>
          <%= pluralize(@post.get_downvotes.size, "Dislike") %>
      <% end %>
      <p class="data">
        <i class="fa fa-comments-o"></i>
        <%= pluralize(@post.comments.count, "Comment") %>
      </p>
      <!-- pass in :id param to 'Edit' and 'Destroy' action -->
      <% if @post.user == current_user %>
          <%= link_to "Edit", edit_post_path(:id => @post.id), class: "data" %>
          <%= link_to "Delete", destroy_path(:id => @post.id), data: {confirm: "Are you sure?"}, class: "data" %>
      <% end %><br>

      <% if @post.comments.count != 0 %>
          <h4>[ Comments ]</h4>
      <% end %>
      <% @comments.each do |c| %>
          <li><p>User ID #<%= c.user_id %> : <b><%= c.msg %></b></p>
            <% if c.user == current_user %>
                <a href="/edit_comment?comment_id=<%= c.id %>" style="color: green">Edit</a> |
                <a href="/destroy_comment?comment_id=<%= c.id %>" style="color: red">Delete</a>
            <% end %>
          </li>
      <% end %>

    </div>
    <%= render 'random_post' %>
  </div>
  <%= render 'form' %>
</div>